### ISSUE TITLE
Правописание порядковых числительных ("-летия" а не " лет")

### ISSUE THREAD

**Issue by d1g** [AMDmi3/streetmangler#22]
Обнаружил что множество названий улиц, которые можно найти на табличках (и в Википедии)

https://ru.wikipedia.org/wiki/Улица_50_лет_Октября - забавно, что на/в Украине преобладает написание "50-летия"
https://ru.wikipedia.org/wiki/Бульвар_50_лет_Октября
https://ru.wikipedia.org/wiki/Проспект_50_лет_Октября
https://ru.wikipedia.org/wiki/Площадь_50_лет_Октября

указаны неверно (в случае "50 лет") согласно http://new.gramota.ru/spravka/letters/87-rubric-99
"верно: 150-летие". У отдельных улиц в Википедии можно найти правильные суффиксы, но их меньшинство.

Поэтому варианты написания с "50-летия" - верны, а остальные - нет.

**Comment by AMDmi3** [comment]
Не вижу почему "50 лет" неверно. "улица 50 лет Октября" (пятидесяти лет) и "улица 50-летия Октября" (пятидесятилетия) - разные названия, оба корректные.
